// Generated by JRun, do not edit


import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import javax.servlet.jsp.tagext.*;
import allaire.jrun.jsp.JRunJSPStaticHelpers;



import java.sql.*;import java.util.*;public class jrun__querybill2ejspe extends allaire.jrun.jsp.HttpJSPServlet implements allaire.jrun.jsp.JRunJspPage 
{  
    private ServletConfig config;
    private ServletContext application;   
    private Object page = this;
    private JspFactory __jspFactory = JspFactory.getDefaultFactory();
    private allaire.jrun.jsp.PageContextPool __pageContextPool;

    public void _jspService(HttpServletRequest request, HttpServletResponse response) 
         throws ServletException, java.io.IOException
    {
        if(config == null) {
            config = getServletConfig();
            application = config.getServletContext(); 
        }
        if(__pageContextPool == null) {
            __pageContextPool = new allaire.jrun.jsp.PageContextPool(application);
        }
        response.setContentType("text/html; charset=ISO-8859-1");
        PageContext pageContext = __jspFactory.getPageContext(this, request, response,  null, true, 8192, true);
        JspWriter out = pageContext.getOut();
        HttpSession session = pageContext.getSession();




        try {


    out.print("\r\n<html>\r\n<body>\r\n");

String com=request.getParameter("Company");
String id=request.getParameter("Id");
String nm=request.getParameter("Name");
String mn=request.getParameter("Month");
String yr=request.getParameter("Year");

//out.print(com);

    out.print("\r\n");

out.print("\r\n");

Class.forName("allaire.jrun.jdbc.JRunDriver");
Connection con=DriverManager.getConnection("jdbc:jrun:sqlserver://127.0.0.1:1433;databaseName=rai","sa","");

//Connection con=DriverManager.getConnection("jdbc:jrun:sqlserver://127.0.0.1:1433;databaseName=rai;user=sa;password=raihan");


    out.print("\r\n\r\n\r\n\r\n\r\n");

out.print("\r\n");

Statement stq =con.createStatement();
	String sqls ="select * from "+com+" where  name= '"+nm+"' and id='"+id+"' and mon='"+mn+"' and yr='"+yr+"' " ;
	
	
ResultSet rss=stq.executeQuery(sqls);   
//out.print(rss.next());


    out.print("\r\n\r\n");

while(rss.next())
	{
	
	String tid=rss.getString(1);
	String tnm=rss.getString(2);
	String tbl=rss.getString(3);
	String tmn=rss.getString(4);
	String tyr=rss.getString(5);
	String tsts=rss.getString(6);
	int total=Integer.parseInt(tbl);
	
	
    out.print("\r\n\t<pre>\r\n\t<font color=\"#000099\" size=\"+3\">\r\n\t");

String comname="****";
			//out.print(comname);
			//out.println("88"+com+"88");
			if(com.equals("ecompany"))
				comname="Electric ";
			
			if(com.equals("wcompany"))
				comname="Water ";
			if(com.equals("gcompany"))
				comname="Gas ";
			
								out.print(comname);
								out.println(" Bill  of  "+tmn+" , "+tyr);

    out.print("\r\n</font></pre>\r\n<table align=\"center\" border=\"2\" bordercolor=\"#000099\">\r\n\r\n<tr><td>Customer ID</td><td>");

out.print(tid);
out.print("</td></tr>\r\n<tr><td>Name</td><td>");

out.print(tnm);
out.print("</td></tr>\r\n<tr><td>Current Month</td><td>");

out.print(tbl);
out.print("</td></tr>\r\n<tr><td>Previous Due</td><td>00000</td></tr>\r\n<tr><td>Late Fee</td><td>00000</td></tr>\r\n<tr><td>Total</td><td>");

out.print(total);
out.print("</td></tr>\r\n<tr><td>Status</td><td>");

out.print(tsts);
out.print("</td></tr>\r\n\r\n");

}

    out.print("\r\n</table>\r\n</body>\r\n</html>\r\n");

      
        } catch(Throwable t) {
            if(t instanceof ServletException)
                throw (ServletException) t;
            if(t instanceof java.io.IOException)
                throw (java.io.IOException) t;
            if(t instanceof RuntimeException)
                throw (RuntimeException) t;
            throw JRunJSPStaticHelpers.handleException(t, pageContext);
    
        } finally { 
            __jspFactory.releasePageContext(pageContext);
        }
    }



  

    public allaire.jrun.jsp.PageContextPool __getPageContextPool()
    {
        return __pageContextPool;
    }
  
    public void __setPageContextPool(allaire.jrun.jsp.PageContextPool p)
    {
        __pageContextPool = p;
    }

    public String __getPagePath()
    {
        return "/querybill.jsp";
    }
}
