// Generated by JRun, do not edit


import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import javax.servlet.jsp.tagext.*;
import allaire.jrun.jsp.JRunJSPStaticHelpers;



import java.util.*;import java.text.DateFormat;import java.sql.Connection;import java.sql.Statement;import java.sql.SQLException;import java.sql.DriverManager;public class jrun__electric2ejspd extends allaire.jrun.jsp.HttpJSPServlet implements allaire.jrun.jsp.JRunJspPage 
{  
    private ServletConfig config;
    private ServletContext application;   
    private Object page = this;
    private JspFactory __jspFactory = JspFactory.getDefaultFactory();
    private allaire.jrun.jsp.PageContextPool __pageContextPool;

    public void _jspService(HttpServletRequest request, HttpServletResponse response) 
         throws ServletException, java.io.IOException
    {
        if(config == null) {
            config = getServletConfig();
            application = config.getServletContext(); 
        }
        if(__pageContextPool == null) {
            __pageContextPool = new allaire.jrun.jsp.PageContextPool(application);
        }
        response.setContentType("text/html; charset=ISO-8859-1");
        PageContext pageContext = __jspFactory.getPageContext(this, request, response,  null, true, 8192, true);
        JspWriter out = pageContext.getOut();
        HttpSession session = pageContext.getSession();




        try {


    out.print("\r\n\r\n<html>\r\n<head>\r\n<title>Electric Bill</title>\r\n</head>\r\n<body>\r\n<pre>\r\n\r\n<p>\t\t\t\r\n\t\t\t<b><font color=\"#330066\" size=\"+2\">\r\n\t\t\tPlease Enter the following informations to pay the Bill.</font></b>\r\n  </p>\r\n<form name=\"form1\" method=\"post\" action=\"\">\r\n");

Date today= new Date();
Locale lc=Locale.US;
DateFormat fmt= DateFormat.getDateInstance(DateFormat.SHORT,Locale.UK);
 String dt=fmt.format(today);


    out.print("\r\n\t\r\n<p>\t\t\t\t\t<input type=\"radio\" name=\"radiobutton\" value=\"radiobutton\"><strong><font color=\"#660000\">Electric Bill\t <input type=\"radio\" name=\"radiobutton\" value=\"radiobutton\">Water Bill  \t<input type=\"radio\" name=\"radiobutton\" value=\"radiobutton\">Gas Bill</font></strong></p><p>&nbsp;</p><p>&nbsp;\t\t\t</p><p>\t\tName   \t\t\t<input type=\"text\" name=\"name\">\t\t\tCustomer ID \t<input type=\"text\" name=\"id\"></p><p></p><p>\t\tBill Amount\t\t<input type=\"text\" name=\"bill\">\t\t\tBank Account No <input type=\"text\" name=\"accno\"></p><p>\t\tPay for \t\tMonth  <select name=\"select\"><option>January </option><option>February</option><option>March</option><option>April</option><option>May</option><option>June</option><option>July</option><option>August</option><option>September</option><option>October</option><option>November</option><option>December</option></select>\t\t\tYear\t\t<input name=\"year\" type=\"text\" value=\"2005\"></p><p>\t\t\t\t\t\t\t\t\t\tPayment Date\t<input type=\"text\" name=\"pdate\" value= \"");

out.print(dt);
out.print("\"></p><p>&nbsp;</p><p>\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"submit\" name=\"Submit\" value=\"Submit\"><input type=\"reset\" name=\"Submit2\" value=\"Reset\"></p></form>\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\r\n<p>\t\t\t\t\t\t\t<object classid=\"clsid:D27CDB6E-AE6D-11cf-96B8-444553540000\" codebase=\"http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=5,0,0,0\" width=\"105\" height=\"23\">\r\n<param name=\"movie\" value=\"button9.swf\"> <param name=\"quality\" value=\"high\">\r\n<param name=\"base\" value=\".\">\r\n<embed src=\"button9.swf\" base=\".\"  quality=\"high\" pluginspage=\"http://www.macromedia.com/shockwave/download/index.cgi?P1_Prod_Version=ShockwaveFlash\" type=\"application/x-shockwave-flash\" width=\"105\" height=\"23\" ></embed>\r\n</object> \t<object classid=\"clsid:D27CDB6E-AE6D-11cf-96B8-444553540000\" codebase=\"http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=5,0,0,0\" width=\"100\" height=\"23\">\r\n<param name=\"movie\" value=\"button15.swf\"> <param name=\"quality\" value=\"high\">\r\n<embed src=\"button15.swf\" quality=\"high\" pluginspage=\"http://www.macromedia.com/shockwave/download/index.cgi?P1_Prod_Version=ShockwaveFlash\" type=\"application/x-shockwave-flash\" width=\"100\" height=\"23\" ></embed>\r\n</object>\t\t</p>\r\n</pre>\r\n");

String nm=request.getParameter("name");
String id=request.getParameter("id");
String bl=request.getParameter("bill");
String accno=request.getParameter("accno");
String mon=request.getParameter("select");
String yr=request.getParameter("year");
String pdt=request.getParameter("pdate");

    out.print("\r\n");

out.print("\r\n");

Class.forName("allaire.jrun.jdbc.JRunDriver");
Connection con=DriverManager.getConnection("jdbc:jrun:sqlserver://127.0.0.1:1433;databaseName=rai","rai","rai");

//Connection con=DriverManager.getConnection("jdbc:jrun:sqlserver://127.0.0.1:1433;databaseName=rai;user=sa;password=raihan");



    out.print("\r\n\r\n\r\n\r\n\r\n");

out.print("\r\n");

try{
		Statement st=con.createStatement();
		st.executeUpdate("insert into electric_t values('"+id+"','"+nm+"','"+bl+"','"+mon+"','"+yr+"','"+pdt+"')");
		}
	
	catch(SQLException se)
	{
	out.print(se);
	}


    out.print("\r\n</body>\r\n</html>\r\n");

      
        } catch(Throwable t) {
            if(t instanceof ServletException)
                throw (ServletException) t;
            if(t instanceof java.io.IOException)
                throw (java.io.IOException) t;
            if(t instanceof RuntimeException)
                throw (RuntimeException) t;
            throw JRunJSPStaticHelpers.handleException(t, pageContext);
    
        } finally { 
            __jspFactory.releasePageContext(pageContext);
        }
    }



  

    public allaire.jrun.jsp.PageContextPool __getPageContextPool()
    {
        return __pageContextPool;
    }
  
    public void __setPageContextPool(allaire.jrun.jsp.PageContextPool p)
    {
        __pageContextPool = p;
    }

    public String __getPagePath()
    {
        return "/electric.jsp";
    }
}
