// Generated by JRun, do not edit


import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import javax.servlet.jsp.tagext.*;
import allaire.jrun.jsp.JRunJSPStaticHelpers;


public class jrun__counter2ejspc extends allaire.jrun.jsp.HttpJSPServlet implements allaire.jrun.jsp.JRunJspPage 
{  
    private ServletConfig config;
    private ServletContext application;   
    private Object page = this;
    private JspFactory __jspFactory = JspFactory.getDefaultFactory();
    private allaire.jrun.jsp.PageContextPool __pageContextPool;

    public void _jspService(HttpServletRequest request, HttpServletResponse response) 
         throws ServletException, java.io.IOException
    {
        if(config == null) {
            config = getServletConfig();
            application = config.getServletContext(); 
        }
        if(__pageContextPool == null) {
            __pageContextPool = new allaire.jrun.jsp.PageContextPool(application);
        }
        response.setContentType("text/html; charset=ISO-8859-1");
        PageContext pageContext = __jspFactory.getPageContext(this, request, response,  null, true, 8192, true);
        JspWriter out = pageContext.getOut();
        HttpSession session = pageContext.getSession();




        try {


    
//@ page session="true" 
    out.print("\r\n<html>\r\n<body>\r\n<h1>COOKIE BASED PAGE COUNTER</h1>\r\n");

int count =1;
Integer parm =(Integer) session.getAttribute("count");
out.print(parm);
if(parm!= null)
{
	count = parm.intValue();
	
}
else
out.print("Page Expired.......");
session.setAttribute("count", new Integer (count+1));
session.setMaxInactiveInterval(3);
if(count==0){

    out.print("\r\nFIRST TIME ACCESS.\r\n");

}

else if(count ==1){

    out.print("\r\nSECOND TIME ACCESS.\r\n");

}
else {

    out.print("\r\nYOU ACCSSED ");

out.print(count);
out.print(" TIMES.\r\n");

}
    out.print("\r\n<p>Click <a href='counter.jsp'>here.</a> \r\n to visit the page again.            \r\n </p>\r\n</body>\r\n</html>\r\n");

      
        } catch(Throwable t) {
            if(t instanceof ServletException)
                throw (ServletException) t;
            if(t instanceof java.io.IOException)
                throw (java.io.IOException) t;
            if(t instanceof RuntimeException)
                throw (RuntimeException) t;
            throw JRunJSPStaticHelpers.handleException(t, pageContext);
    
        } finally { 
            __jspFactory.releasePageContext(pageContext);
        }
    }



  

    public allaire.jrun.jsp.PageContextPool __getPageContextPool()
    {
        return __pageContextPool;
    }
  
    public void __setPageContextPool(allaire.jrun.jsp.PageContextPool p)
    {
        __pageContextPool = p;
    }

    public String __getPagePath()
    {
        return "/counter.jsp";
    }
}
