// Generated by JRun, do not edit


import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import javax.servlet.jsp.tagext.*;
import allaire.jrun.jsp.JRunJSPStaticHelpers;



import java.sql.*;public class jrun__request2ejspc extends allaire.jrun.jsp.HttpJSPServlet implements allaire.jrun.jsp.JRunJspPage 
{  
    private ServletConfig config;
    private ServletContext application;   
    private Object page = this;
    private JspFactory __jspFactory = JspFactory.getDefaultFactory();
    private allaire.jrun.jsp.PageContextPool __pageContextPool;

    public void _jspService(HttpServletRequest request, HttpServletResponse response) 
         throws ServletException, java.io.IOException
    {
        if(config == null) {
            config = getServletConfig();
            application = config.getServletContext(); 
        }
        if(__pageContextPool == null) {
            __pageContextPool = new allaire.jrun.jsp.PageContextPool(application);
        }
        response.setContentType("text/html; charset=ISO-8859-1");
        PageContext pageContext = __jspFactory.getPageContext(this, request, response,  null, true, 8192, true);
        JspWriter out = pageContext.getOut();
        HttpSession session = pageContext.getSession();




        try {


    out.print("\r\n");

String colors[] ={"E0E0E0","F0F0F0"};  

 String [][] TABS ={
{
"HD",
"Headers"
,"ShowRequestHeaders.jsp"
},

{
"PM",
"Parameters"
,"ShowParameters.jsp"
},
{
"SR",
"ServletRequest Methods"
,"ShowServletRequestMethodValues.jsp"
}
};

    out.print("\r\n<html>\r\n<head>\r\n<title>REQUEST</title>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\">\r\n</head>\r\n\r\n<body>\r\n\r\n<h2 SHOW REQUEST </h2>\r\n<form>\r\n");

String which = request.getParameter("which");
if(which == null)which =TABS[0][0];
String jspToRun =null;

for(int i=0;i<TABS.length;i++)
{
String tabCode = TABS[i][0];
String tabLabel = TABS[i][1];
String tabJsp = TABS[i][2];
String CHECKED ="";

if(which.equals(tabCode)){
CHECKED="CHECKED";
jspToRun =tabJsp;
 
}

    out.print("\r\n\r\n<input name=\" which\" type=\"radio\" value=\"");

out.print(tabCode);
out.print("\" \r\n\t\t\t");

out.print(CHECKED);
out.print(" onClick=\" this.form.submit()\">\r\n\t\t\t");

out.print(tabLabel);
out.print("\r\n\t\t\t\r\n\t\t\t");

} 
    out.print("\r\n\t\t\t\r\n\t\t\t\r\n");
out.flush();


pageContext.include( jspToRun + "");
out.print("\r\n\r\n\r\n \r\n\r\n}\r\n\r\n\r\n\r\n\r\n\r\n%>\r\n\r\n\r\n\r\n</form>\r\n\r\n</body>\r\n</html>\r\n");

      
        } catch(Throwable t) {
            if(t instanceof ServletException)
                throw (ServletException) t;
            if(t instanceof java.io.IOException)
                throw (java.io.IOException) t;
            if(t instanceof RuntimeException)
                throw (RuntimeException) t;
            throw JRunJSPStaticHelpers.handleException(t, pageContext);
    
        } finally { 
            __jspFactory.releasePageContext(pageContext);
        }
    }



  

    public allaire.jrun.jsp.PageContextPool __getPageContextPool()
    {
        return __pageContextPool;
    }
  
    public void __setPageContextPool(allaire.jrun.jsp.PageContextPool p)
    {
        __pageContextPool = p;
    }

    public String __getPagePath()
    {
        return "/request.jsp";
    }
}
