// Generated by JRun, do not edit


import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import javax.servlet.jsp.tagext.*;
import allaire.jrun.jsp.JRunJSPStaticHelpers;


public class jrun__pass2ejsp9 extends allaire.jrun.jsp.HttpJSPServlet implements allaire.jrun.jsp.JRunJspPage 
{  
    private ServletConfig config;
    private ServletContext application;   
    private Object page = this;
    private JspFactory __jspFactory = JspFactory.getDefaultFactory();
    private allaire.jrun.jsp.PageContextPool __pageContextPool;

    public void _jspService(HttpServletRequest request, HttpServletResponse response) 
         throws ServletException, java.io.IOException
    {
        if(config == null) {
            config = getServletConfig();
            application = config.getServletContext(); 
        }
        if(__pageContextPool == null) {
            __pageContextPool = new allaire.jrun.jsp.PageContextPool(application);
        }
        response.setContentType("text/html; charset=ISO-8859-1");
        PageContext pageContext = __jspFactory.getPageContext(this, request, response,  null, true, 8192, true);
        JspWriter out = pageContext.getOut();
        HttpSession session = pageContext.getSession();




        try {


    out.print("<html>\r\n\r\n<body>\r\n\r\n\r\n<form name=\"form1\" method=\"post\" action=\"pass.jsp\">\r\n\r\n\t<input type=\"text\" name=\"Name\">\r\n\r\n<input type=\"submit\" name=\"Submit\" value=\"Sub\">\r\n\r\n</form>\r\n\r\n\r\n");

String r=request.getParameter("Name");

String a="a";

String b="a1111";

//if(a.equals(rr))
//out.println("equal");
//else
//out.println("not");


//Double d=new Double(d1);


try{
int d1=Integer.parseInt(r);

out.print(d1);
//out.print(d1.isNaN());
}

catch(NumberFormatException n)
{
out.print(n);

}

    out.print("\r\n\r\n\r\n\r\n\r\n\r\n</body>\r\n\r\n</html>");

      
        } catch(Throwable t) {
            if(t instanceof ServletException)
                throw (ServletException) t;
            if(t instanceof java.io.IOException)
                throw (java.io.IOException) t;
            if(t instanceof RuntimeException)
                throw (RuntimeException) t;
            throw JRunJSPStaticHelpers.handleException(t, pageContext);
    
        } finally { 
            __jspFactory.releasePageContext(pageContext);
        }
    }



  

    public allaire.jrun.jsp.PageContextPool __getPageContextPool()
    {
        return __pageContextPool;
    }
  
    public void __setPageContextPool(allaire.jrun.jsp.PageContextPool p)
    {
        __pageContextPool = p;
    }

    public String __getPagePath()
    {
        return "/pass.jsp";
    }
}
