// Generated by JRun, do not edit


import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import javax.servlet.jsp.tagext.*;
import allaire.jrun.jsp.JRunJSPStaticHelpers;



import java.sql.*;public class jrun__tabselect2ejspe extends allaire.jrun.jsp.HttpJSPServlet implements allaire.jrun.jsp.JRunJspPage 
{  
    private ServletConfig config;
    private ServletContext application;   
    private Object page = this;
    private JspFactory __jspFactory = JspFactory.getDefaultFactory();
    private allaire.jrun.jsp.PageContextPool __pageContextPool;

    public void _jspService(HttpServletRequest request, HttpServletResponse response) 
         throws ServletException, java.io.IOException
    {
        if(config == null) {
            config = getServletConfig();
            application = config.getServletContext(); 
        }
        if(__pageContextPool == null) {
            __pageContextPool = new allaire.jrun.jsp.PageContextPool(application);
        }
        response.setContentType("text/html; charset=ISO-8859-1");
        PageContext pageContext = __jspFactory.getPageContext(this, request, response,  null, true, 8192, true);
        JspWriter out = pageContext.getOut();
        HttpSession session = pageContext.getSession();




        try {


    out.print("\r\n<html>\r\n<head>\r\n<title>Table Select</title>\r\n</head>\r\n\r\n<body>\r\n");

out.print("\r\n");

Class.forName("allaire.jrun.jdbc.JRunDriver");
Connection con=DriverManager.getConnection("jdbc:jrun:sqlserver://127.0.0.1:1433;databaseName=rai","sa","");

//Connection con=DriverManager.getConnection("jdbc:jrun:sqlserver://127.0.0.1:1433;databaseName=rai;user=sa;password=raihan");


    out.print("\r\n\r\n\r\n\r\n\r\n");

out.print("\r\n");

try{
	
	String user=request.getParameter("user");
	Statement st =con.createStatement();
	
	String sqlshow ="select * from newuser where name='"+user+"' " ;
	
	ResultSet rss=st.executeQuery(sqlshow);   

	
    out.print("\r\n\t<table border=\"1\" align=\"center\" bordercolor=\"#00CCCC\" >\r\n\t");

while(rss.next())
	{
	String name=rss.getString(1);
	String ad=rss.getString(2);
	String bd=rss.getString(3);
	String na=rss.getString(4);
	String oc=rss.getString(5);
	String ph=rss.getString(6);
	String em=rss.getString(7);
	String baln=rss.getString(8);
	String acno=rss.getString(10);
	
	
    out.print("\r\n\t<br>\r\n\t<br>\r\n\t<br>\r\n\t<br>\r\n\t\r\n\t<tr><td>Name </td><td>");

out.print(name);
out.print("</td></tr>\r\n\t<tr><td>Address </td><td>");

out.print(ad);
out.print("</td></tr>\r\n\t<tr><td>Birthdate </td><td>");

out.print(bd);
out.print("</td></tr>\r\n\t<tr><td>Nationality </td><td>");

out.print(na);
out.print("</td></tr>\r\n\t<tr><td>Occupation </td><td>");

out.print(oc);
out.print("</td></tr>\r\n\t<tr><td>Phone </td><td>");

out.print(ph);
out.print("</td></tr>\r\n\t<tr><td>Email </td><td>");

out.print(em);
out.print("</td></tr>\r\n\t<tr><td>Account No </td><td>");

out.print(acno);
out.print("</td></tr>\r\n\t<tr><td>Balance </td><td>");

out.print(baln);
out.print("</td></tr>\r\n\t\r\n");

}


    out.print("\r\n\r\n</table>\r\n");

}

catch(SQLException se)
{
out.println(se);
}


    out.print("\r\n\r\n\r\n\r\n\r\n\r\n\r\n</body>\r\n</html>\r\n");

      
        } catch(Throwable t) {
            if(t instanceof ServletException)
                throw (ServletException) t;
            if(t instanceof java.io.IOException)
                throw (java.io.IOException) t;
            if(t instanceof RuntimeException)
                throw (RuntimeException) t;
            throw JRunJSPStaticHelpers.handleException(t, pageContext);
    
        } finally { 
            __jspFactory.releasePageContext(pageContext);
        }
    }



  

    public allaire.jrun.jsp.PageContextPool __getPageContextPool()
    {
        return __pageContextPool;
    }
  
    public void __setPageContextPool(allaire.jrun.jsp.PageContextPool p)
    {
        __pageContextPool = p;
    }

    public String __getPagePath()
    {
        return "/tabselect.jsp";
    }
}
