// Generated by JRun, do not edit


import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import javax.servlet.jsp.tagext.*;
import allaire.jrun.jsp.JRunJSPStaticHelpers;



import java.sql.*;public class jrun__Admin2ejspa extends allaire.jrun.jsp.HttpJSPServlet implements allaire.jrun.jsp.JRunJspPage 
{  
    private ServletConfig config;
    private ServletContext application;   
    private Object page = this;
    private JspFactory __jspFactory = JspFactory.getDefaultFactory();
    private allaire.jrun.jsp.PageContextPool __pageContextPool;

    public void _jspService(HttpServletRequest request, HttpServletResponse response) 
         throws ServletException, java.io.IOException
    {
        if(config == null) {
            config = getServletConfig();
            application = config.getServletContext(); 
        }
        if(__pageContextPool == null) {
            __pageContextPool = new allaire.jrun.jsp.PageContextPool(application);
        }
        response.setContentType("text/html; charset=ISO-8859-1");
        PageContext pageContext = __jspFactory.getPageContext(this, request, response,  null, true, 8192, true);
        JspWriter out = pageContext.getOut();
        HttpSession session = pageContext.getSession();




        try {


    out.print("\r\n<html>\r\n\r\n<body>\r\n<pre>\r\n<form name=\"form1\" method=\"post\" action=\"Adconnection.jsp\">\r\n                     <p><b>  <font color=\"#009900\" size=\"+2\">\t\r\n\t\t\t\t\tPlease Enter Your Name &amp; Password.</font></b></p><p>&nbsp;</p><p>&nbsp;</p><p>&nbsp;</p><p>&nbsp;</p><p><font color=\"#660000\">\t\t\t\t\tManager Name     <input type=\"text\" name=\"user\"></p></font></p><font color=\"#660000\"><p>&nbsp;</p><p>\t\t\t\t\tPassword\t <input type=\"password\" name=\"pass\">\r\n</p></font><p>&nbsp;\t\t\t\t\t\t\t\t</p><p>&nbsp;</p><p>\t\t\t\t\t\t\t   <input type=\"submit\" name=\"submit\" value=\"Submit\" ><input type=\"reset\" name=\"reset\" value=\"Reset\"></p></form>\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n</pre>\r\n\r\n\r\n\r\n</body>\r\n</html>\r\n");

      
        } catch(Throwable t) {
            if(t instanceof ServletException)
                throw (ServletException) t;
            if(t instanceof java.io.IOException)
                throw (java.io.IOException) t;
            if(t instanceof RuntimeException)
                throw (RuntimeException) t;
            throw JRunJSPStaticHelpers.handleException(t, pageContext);
    
        } finally { 
            __jspFactory.releasePageContext(pageContext);
        }
    }



  

    public allaire.jrun.jsp.PageContextPool __getPageContextPool()
    {
        return __pageContextPool;
    }
  
    public void __setPageContextPool(allaire.jrun.jsp.PageContextPool p)
    {
        __pageContextPool = p;
    }

    public String __getPagePath()
    {
        return "/Admin.jsp";
    }
}
