// Generated by JRun, do not edit


import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import javax.servlet.jsp.tagext.*;
import allaire.jrun.jsp.JRunJSPStaticHelpers;



import java.sql.*;
import java.sql.*;public class jrun__post2ejsp9 extends allaire.jrun.jsp.HttpJSPServlet implements allaire.jrun.jsp.JRunJspPage 
{  
    private ServletConfig config;
    private ServletContext application;   
    private Object page = this;
    private JspFactory __jspFactory = JspFactory.getDefaultFactory();
    private allaire.jrun.jsp.PageContextPool __pageContextPool;

    public void _jspService(HttpServletRequest request, HttpServletResponse response) 
         throws ServletException, java.io.IOException
    {
        if(config == null) {
            config = getServletConfig();
            application = config.getServletContext(); 
        }
        if(__pageContextPool == null) {
            __pageContextPool = new allaire.jrun.jsp.PageContextPool(application);
        }
        response.setContentType("text/html; charset=ISO-8859-1");
        PageContext pageContext = __jspFactory.getPageContext(this, request, response,  null, true, 8192, true);
        JspWriter out = pageContext.getOut();
        HttpSession session = pageContext.getSession();




        try {


    out.print("\r\n<html>\r\n\r\n<body>\r\n");

out.print("\r\n");

Class.forName("allaire.jrun.jdbc.JRunDriver");
Connection con=DriverManager.getConnection("jdbc:jrun:sqlserver://127.0.0.1:1433;databaseName=rai","sa","");

//Connection con=DriverManager.getConnection("jdbc:jrun:sqlserver://127.0.0.1:1433;databaseName=rai;user=sa;password=raihan");


    out.print("\r\n\r\n\r\n\r\n\r\n");

out.print("\r\n\r\n");

String st=request.getParameter("Status");

String cm=request.getParameter("Company");
String id=request.getParameter("Id");
String nm=request.getParameter("Name");
String bl=request.getParameter("Bill");
String mon=request.getParameter("Month");
String yr=request.getParameter("Year");



    out.print("\r\n");

String com_t=null;
if(cm.equals("pdb"))
	 com_t="ecompany" ;
	
 if(cm.equals("wasa"))
	com_t="wcompany" ;

if	(cm.equals("titas"))
	com_t="gcompany" ;

//out.print(com_t);
///com_t="ecompany" ;
//out.print(com_t);

    out.print("\r\n\r\n\r\n\r\n\r\n");

try{
		Statement stp=con.createStatement();
		stp.executeUpdate("insert into "+com_t+" values('"+id+"','"+nm+"','"+bl+"','"+mon+"','"+yr+"','"+st+"')");
		}
	
		catch(SQLException se)
		{
		out.print(se);
		}


    out.print("\r\n<pre>\r\n\t\t\t\t\t\t<font color=\"#990000\" size=\"+2\">   ");

out.print("Bill Created");
    out.print("</font>\r\n</pre>\r\n<table border=\"2\" align=\"center\" bordercolor=\"#000066\">\r\n\r\n<tr><td>Customer ID</td> <td>");

out.print(id);
out.print("</td></tr>\r\n<tr><td>Customer Name</td> <td>");

out.print(nm);
out.print("</td></tr>\r\n<tr><td>Bill Amount</td> <td>");

out.print(bl);
out.print("</td></tr>\r\n<tr><td>Pay Month</td> <td>");

out.print(mon);
out.print("</td></tr>\r\n<tr><td>Pay Year</td> <td>");

out.print(yr);
out.print("</td></tr>\r\n\r\n\r\n\r\n</table>\r\n\r\n\r\n<pre>\r\n\t\t\t\t\t\t\r\n\t\t\t\t\t\t<font color=\"#990000\" size=\"+2\"> ");

out.print("Create New User Bill.");
    out.print("</font>\r\n</pre>\r\n\r\n\r\n\t\t\t\t\t\t\t\t");

out.print("\r\n");

String com =request.getParameter("Company");
    out.print("\r\n<form name=\"form1\" method=\"post\" action=\"post.jsp\">\r\n  <pre>\t\t\t\t\t\t\t\t\t\t\t\t\r\n\r\n\r\n\t\t\t\t\tCustomer ID\t\t\t<input type=\"text\" name=\"Id\">\r\n\t\t\t\t\t\t\r\n\t\t\t\t\tName\t\t\t\t<input type=\"text\" name=\"Name\" >\r\n\t\r\n\t\t\t\t\tBill\t\t\t\t<input type=\"text\" name=\"Bill\">\r\n\t\t\t\t\t\r\n\t\t\t\t\t\t\t<input type=\"hidden\" name=\"Company\" value=\"");

out.print(com);
out.print("\">\t\t<input type=\"hidden\" name=\"Status\" value=\"due\">\r\n\r\n\t\t\t\t\tPay Month \t  \t<select name=\"Month\"><option>January</option><option>February</option><option>March</option><option>April</option><option>May</option><option>June</option><option>July</option><option>August</option><option>September</option><option>October</option><option>November</option><option>December</option></select>  Year <select name=\"Year\"><option>2005</option><option>2006</option></select>\r\n  \t\t\t\t\r\n\t\r\n       \t  \t\t\t\t\t\t\t\t    <input type=\"submit\" name=\"Submit\" value=\"Submit\"><input type=\"reset\" name=\"Submit2\" value=\"Reset\">\r\n</pre>\r\n</form>\r\n\r\n\r\n");

out.print("\r\n\r\n</body>\r\n</html>\r\n");

      
        } catch(Throwable t) {
            if(t instanceof ServletException)
                throw (ServletException) t;
            if(t instanceof java.io.IOException)
                throw (java.io.IOException) t;
            if(t instanceof RuntimeException)
                throw (RuntimeException) t;
            throw JRunJSPStaticHelpers.handleException(t, pageContext);
    
        } finally { 
            __jspFactory.releasePageContext(pageContext);
        }
    }



  

    public allaire.jrun.jsp.PageContextPool __getPageContextPool()
    {
        return __pageContextPool;
    }
  
    public void __setPageContextPool(allaire.jrun.jsp.PageContextPool p)
    {
        __pageContextPool = p;
    }

    public String __getPagePath()
    {
        return "/post.jsp";
    }
}
