// Generated by JRun, do not edit


import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import javax.servlet.jsp.tagext.*;
import allaire.jrun.jsp.JRunJSPStaticHelpers;



import java.sql.*;public class jrun__Updateinsert2ejsp11 extends allaire.jrun.jsp.HttpJSPServlet implements allaire.jrun.jsp.JRunJspPage 
{  
    private ServletConfig config;
    private ServletContext application;   
    private Object page = this;
    private JspFactory __jspFactory = JspFactory.getDefaultFactory();
    private allaire.jrun.jsp.PageContextPool __pageContextPool;

    public void _jspService(HttpServletRequest request, HttpServletResponse response) 
         throws ServletException, java.io.IOException
    {
        if(config == null) {
            config = getServletConfig();
            application = config.getServletContext(); 
        }
        if(__pageContextPool == null) {
            __pageContextPool = new allaire.jrun.jsp.PageContextPool(application);
        }
        response.setContentType("text/html; charset=ISO-8859-1");
        PageContext pageContext = __jspFactory.getPageContext(this, request, response,  null, true, 8192, true);
        JspWriter out = pageContext.getOut();
        HttpSession session = pageContext.getSession();




        try {


    out.print("\r\n<html>\r\n<head>\r\n<title>insert user</title>\r\n<meta http-equiv=\"refresh\" >\r\n</head>\r\n<body>\r\n\r\n\r\n");

out.print("\r\n");

Class.forName("allaire.jrun.jdbc.JRunDriver");
Connection con=DriverManager.getConnection("jdbc:jrun:sqlserver://127.0.0.1:1433;databaseName=rai","sa","");

//Connection con=DriverManager.getConnection("jdbc:jrun:sqlserver://127.0.0.1:1433;databaseName=rai;user=sa;password=raihan");


    out.print("\r\n\r\n\r\n\r\n\r\n");

out.print("\r\n");

//cnt =(String)
 //out.print(session.getAttribute("count"));
 //if(session.getAttribute("count")!=null)
	
 //=new Integer();
 //cnt=p.intValue(); 
	
	try{
	 	//out.print(session.getAttribute("count"));
		if(session.getAttribute("ucount")!=null)
	 	{
	 				
//out.print(cnt);

//if(cnt.equals(session.getAttribute("count")))
//out.print("PAGE EXPIRED>>>>>>>>>>");


    out.print("\r\n\r\n");

String acno=request.getParameter("Accno");
String nam=request.getParameter("Name");
String ad=request.getParameter("Address");
String bd=request.getParameter("Birthday");
String na=request.getParameter("Nationality");
String oc=request.getParameter("Occupation");
String ph=request.getParameter("Phone");
String em=request.getParameter("Email");
String pas=request.getParameter("Password");
String repas=request.getParameter("Repassword");
String balc =request.getParameter("Balance");


    out.print("\r\n\r\n\r\n");

if(pas.equals(repas))
{
out.println("\n Check out the informations.");

    out.print("\r\n\r\n");

out.print("<p>&nbsp;</p><table border=\"2\" bordercolor=\"#3366FF\" >\r\n\r\n\r\n<tr>\r\n<td >Name     </td>\r\n<td >");

out.print(nam);
out.print("   </td>\r\n</tr>\r\n\r\n\r\n<tr>\r\n<td >Address     </td>\r\n<td >");

out.print(ad);
out.print("   </td>\r\n</tr>\r\n\r\n<tr>\r\n<td >Birthdate     </td>\r\n<td >");

out.print(bd);
out.print("   </td>\r\n</tr>\r\n\r\n\r\n<tr>\r\n<td >Nationality     </td>\r\n<td >");

out.print(na);
out.print("   </td>\r\n</tr>\r\n\r\n\r\n<tr>\r\n<td >Occupation     </td>\r\n<td >");

out.print(oc);
out.print("   </td>\r\n</tr>\r\n\r\n\r\n<tr>\r\n<td >Phone    </td>\r\n<td >");

out.print(ph);
out.print("   </td>\r\n</tr>\r\n\r\n\r\n<tr>\r\n<td >Email     </td>\r\n<td >");

out.print(em);
out.print("   </td>\r\n</tr>\r\n\r\n<td >Balance     </td>\r\n<td >");

out.print(balc);
out.print("   </td>\r\n</tr>\r\n\r\n\r\n<td >Password     </td>\r\n<td >");

out.print(pas);
out.print("   </td>\r\n</tr>\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n</table>\r\n\r\n");

out.print("\r\n");

}

    out.print("\r\n\r\n\r\n\r\n\r\n\r\n");

try
{
Statement st =con.createStatement();

String sql ="updateuser '"+nam+"','"+ad+"','"+bd+"','"+na+"','"+oc+"','"+ph+"','"+em+"','"+balc+"' ,'"+pas+"','"+acno+"'" ;
st.executeUpdate(sql);
//out.println("New User has been Created.");



    out.print("\r\n");

}

catch(SQLException se)
{
out.println(se);
}

    out.print("\r\n\r\n");

}



else
out.print("The Page has Expired. Please log in again..");


}

catch(Exception e)
{

out.print(e);

}



    out.print("\r\n<p>&nbsp; </p>\r\n<p>&nbsp;</p>\r\n</body>\r\n</html>\r\n");

      
        } catch(Throwable t) {
            if(t instanceof ServletException)
                throw (ServletException) t;
            if(t instanceof java.io.IOException)
                throw (java.io.IOException) t;
            if(t instanceof RuntimeException)
                throw (RuntimeException) t;
            throw JRunJSPStaticHelpers.handleException(t, pageContext);
    
        } finally { 
            __jspFactory.releasePageContext(pageContext);
        }
    }



  

    public allaire.jrun.jsp.PageContextPool __getPageContextPool()
    {
        return __pageContextPool;
    }
  
    public void __setPageContextPool(allaire.jrun.jsp.PageContextPool p)
    {
        __pageContextPool = p;
    }

    public String __getPagePath()
    {
        return "/Updateinsert.jsp";
    }
}
